package P2.EvenFibonacciNumbers;

public class Main {

	public static long fibonacci(int n) {
		if (n <= 1)
			return n;
		else
			return fibonacci(n - 1) + fibonacci(n - 2);
	}

	public static void main(String[] args) {

		/*
		 * Each new term in the Fibonacci sequence is generated by adding the
		 * previous two terms. By starting with 1 and 2, the first 10 terms will
		 * be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms
		 * in the Fibonacci sequence whose values do not exceed four million,
		 * find the sum of the even-valued terms.
		 */

		int n = 33;
		int sum = 0;
		for (int i = 1; i <= n; i++) {
			//System.out.println(i + ": " + fibonacci(i));
			
			if(fibonacci(i) % 2 == 0){
				System.out.println(i + ": " + fibonacci(i));
				
				sum += fibonacci(i);
				System.out.println("sum: " + sum);
			}
		}
	}

}
